defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:11.11

# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '~/app'
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: 'Install node modules'
          command: npm install
      - run:
          name: 'Build app'
          command: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - build
            - package.json
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - attach_workspace:
          at: ~/app
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run:
          name: Install awscli
          command: sudo pip install awscli --upgrade
      - run:
          name: Upload main sourcemap to Rollbar
          command: |
            main_source_map=`find build/static/js -name main.*.chunk.js.map -print`
            main_source=${main_source_map%.map}
            main_source_url=$DOMAIN_ROOT${main_source#build/}
            curl https://api.rollbar.com/api/1/sourcemap/ \
            -F access_token=$ROLLBAR_POST_SERVER_ITEM_TOKEN \
            -F version=`git rev-parse HEAD` \
            -F minified_url=$main_source_url \
            -F source_map=@$main_source_map
      - run:
          name: Upload secondary sourcemap to Rollbar
          command: |
            secondary_source_map=`find build/static/js -name 2.*.chunk.js.map -print`
            secondary_source=${secondary_source_map%.map}
            secondary_source_url=$DOMAIN_ROOT${secondary_source#build/}
            curl https://api.rollbar.com/api/1/sourcemap/ \
            -F access_token=$ROLLBAR_POST_SERVER_ITEM_TOKEN \
            -F version=`git rev-parse HEAD` \
            -F minified_url=$secondary_source_url \
            -F source_map=@$secondary_source_map
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync build/ s3://async-web --cache-control max-age=172800 --delete
            aws s3 cp s3://async-web/index.html s3://async-web/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html
