import { faLaugh, faSquare } from '@fortawesome/free-regular-svg-icons';
import {
  faPlusCircle as faRegularPlusCircle,
  faTimes,
  faCommentLines as faRegularCommentLines,
} from '@fortawesome/pro-regular-svg-icons';
import {
  faArrowCircleRight as faSolidArrowCircleRight,
  faBold,
  faCheckSquare,
  faCode,
  faComment,
  faCompressAlt,
  faEdit,
  faHeading,
  faImage,
  faItalic,
  faLayerGroup,
  faListOl,
  faListUl,
  faLock,
  faQuoteRight,
  faReply,
  faTasks,
  faTerminal,
  faTrash,
  faUser,
  faUsers,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBell,
  faCommentsAlt,
  faCommentCheck,
  faCommentLines as faSolidCommentLines,
  faCommentPlus,
  faFileAlt,
  faHorizontalRule,
  faLongArrowDown,
  faPlus as faSolidPlus,
  faText,
} from '@fortawesome/pro-solid-svg-icons';
import {
  faArrowCircleRight as faLightArrowCircleRight,
  faCommentsAlt as faLightCommentsAlt,
  faCommentLines,
  faFontCase,
  faFileSearch,
  faInfinity,
  faPlus as faLightPlus,
  faPlusCircle as faLightPlusCircle,
  faUserCircle,
} from '@fortawesome/pro-light-svg-icons';

export default [
  faBell,
  faBold,
  faCheckSquare,
  faCode,
  faComment,
  faCommentsAlt,
  faCommentCheck,
  faCommentLines,
  faRegularCommentLines,
  faSolidCommentLines,
  faCommentPlus,
  faCompressAlt,
  faEdit,
  faFileAlt,
  faFileSearch,
  faFontCase,
  faHeading,
  faHorizontalRule,
  faImage,
  faItalic,
  faInfinity,
  faLaugh,
  faLayerGroup,
  faLightArrowCircleRight,
  faLightCommentsAlt,
  faLightPlus,
  faLightPlusCircle,
  faListOl,
  faListUl,
  faLock,
  faLongArrowDown,
  faQuoteRight,
  faRegularCommentLines,
  faRegularPlusCircle,
  faReply,
  faSolidArrowCircleRight,
  faSolidPlus,
  faSquare,
  faTasks,
  faTerminal,
  faText,
  faTimes,
  faTrash,
  faUser,
  faUserCircle,
  faUsers,
];
