import { faLaugh, faSquare } from '@fortawesome/free-regular-svg-icons';
import {
  faArrowCircleRight as faSolidArrowCircleRight,
  faBold,
  faCheckSquare,
  faCode,
  faEdit,
  faHeading,
  faImage,
  faItalic,
  faListOl,
  faListUl,
  faQuoteRight,
  faTasks,
  faTerminal,
  faTrash,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBell,
  faCommentsAlt,
  faCommentCheck,
  faCommentPlus,
  faFileAlt,
  faHorizontalRule,
  faPlus as faSolidPlus,
  faText,
} from '@fortawesome/pro-solid-svg-icons';
import {
  faArrowCircleRight as faLightArrowCircleRight,
  faCommentsAlt as faLightCommentsAlt,
  faCommentLines,
  faFontCase,
  faFileSearch,
  faInfinity,
  faPlus as faLightPlus,
  faPlusCircle,
  faUserCircle,
} from '@fortawesome/pro-light-svg-icons';

export default [
  faBell,
  faBold,
  faCheckSquare,
  faCode,
  faCommentsAlt,
  faCommentCheck,
  faCommentLines,
  faCommentPlus,
  faEdit,
  faFileAlt,
  faFontCase,
  faHeading,
  faHorizontalRule,
  faImage,
  faItalic,
  faInfinity,
  faLaugh,
  faLightArrowCircleRight,
  faLightCommentsAlt,
  faLightPlus,
  faListOl,
  faListUl,
  faPlusCircle,
  faQuoteRight,
  faSolidArrowCircleRight,
  faSolidPlus,
  faFileSearch,
  faSquare,
  faTasks,
  faTerminal,
  faText,
  faTrash,
  faUserCircle,
];
